PhotoLikers/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from photo_likers.loading_startup_cache import load_start_cache

urlpatterns = [
    url(r'^', include('photo_likers.urls')),
    url(r'^admin/', admin.site.urls),
]

load_start_cache()

photo_likers/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login

app_name = 'photo_likers'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^photos/sort=(?P<sort_field>[0-1])&tags=(?P<tags_list>[0-9|;|-]*)&page=(?P<page_number>[0-9]+)$',
        views.photos_view, name='photos'),
    url(r'^login/$', login, name='login'),
]

photo_likers/models.py
from django.db.models import *
from django.conf import settings


class Tag(Model):
    name = CharField(max_length=50)

    class Meta:
        managed = True
        app_label = 'photo_likers'


class Photo(Model):
    path = CharField(max_length=200)
    likes_cnt = IntegerField(db_index=True)
    created_date = DateField(db_index=True)
    tags = ManyToManyField(Tag, verbose_name="Tags")


class PhotoLikes(Model):
    photo = ForeignKey(Photo)
    user = ForeignKey(settings.AUTH_USER_MODEL)
    like_date = DateField()

photo_likers/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render

from photo_likers.models import Tag
from photo_likers.utils.photo_request import PhotosRequest
from .page_searcher import PageSearcher
from .cache_manager import CacheManager


def index(request: HttpRequest):
    return HttpResponse("Hello, world!")


@login_required
def photos_view(request: HttpRequest, page_number: str = "1", sort_field: str = "0",
                tags_list: str = "") -> HttpResponse:
    """Основная view

    :param request: HttpRequest
    :param page_number: номер страницы
    :param sort_field: 0-сортировка по лайкам, 1-по дате
    :param tags_list: список тегов через ";" со знаком - или без
    :return: HttpResponse
    """
    photo_request = PhotosRequest(page_number=page_number, sort_field=sort_field, tags_conditions=tags_list, tags = Tag.objects.all())
    tag_refs = photo_request.get_tag_conditions_references()

    sorted_cache = CacheManager.get_sorted_photo_cache(photo_request)
    page = PageSearcher(sorted_cache).get_pagination_by_request(photo_request)

    return render(request, 'photos.html',
                  {'photos': page, 'page_number': page_number, 'sort_field': sort_field, 'tags_list': tags_list,
                   'tag_refs': tag_refs})

photo_likers/templates/photos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Photos</title>
</head>
<body>
<div>
    <a href="{% url 'photo_likers:photos' 0 tags_list  photos.number %}">Sort by likes</a>
    <a href="{% url 'photo_likers:photos' 1 tags_list  photos.number %}">Sort by date</a>
</div>
{% for tag in tag_refs %}
    <a href="{% url 'photo_likers:photos' sort_field tag.ref 1 %}"> {{ tag.ref_name }} </a>
{% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if photos.has_previous %}
            <a href="{% url 'photo_likers:photos' sort_field tags_list photos.previous_page_number %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ photos.number }} of {{ photos.paginator.num_pages }}.
        </span>

        {% if photos.has_next %}
            <a href="{% url 'photo_likers:photos' sort_field tags_list  photos.next_page_number %}">next</a>
        {% endif %}
    </span>
</div>

{% for photo in photos %}
<figure>
    <img src="{{ photo.path }}" style="width:304px;height:228px;" />
    <figcaption>Likes {{ photo.likes_cnt }}; Date {{ photo.created_date }}</figcaption>
</figure>
{% endfor %}

</body>
</html>